# Generated by Django 5.2.8 on 2025-11-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"permissions": [("can_publish", "Can publish posts")]},
        ),
    ]
